apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - api.midominio.com
    secretName: api-tls-secret
  rules:
  - host: api.midominio.com
    http:
      paths:
      - path: /valoraciones(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: valoraciones-service
            port:
              number: 80
      - path: /consultas(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: consultas-service
            port:
              number: 80
